// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "bedd9b80-5973-4f77-af85-4e11287fc214";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDeviceStatusChange();
void onFirmwareVersionCloudChange();
void onOtaCounterChange();
void onLedStateChange();

String deviceStatus;
String firmwareVersionCloud;
int otaCounter;
bool ledState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(deviceStatus, READWRITE, ON_CHANGE, onDeviceStatusChange);
  ArduinoCloud.addProperty(firmwareVersionCloud, READWRITE, ON_CHANGE, onFirmwareVersionCloudChange);
  ArduinoCloud.addProperty(otaCounter, READWRITE, ON_CHANGE, onOtaCounterChange);
  ArduinoCloud.addProperty(ledState, READWRITE, ON_CHANGE, onLedStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
